version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "input-topic:1:1 intermediate-topic:1:1 output-topic:1:1"
      ALLOW_PLAINTEXT_LISTENER: 'yes'

  kafka-processor-1:
    build: ./processor1
    container_name: kafka-processor-1
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - ./processor1:/app
    working_dir: /app
    command: python3 kafka_script.py

  kafka-processor-2:
    build: ./processor2
    container_name: kafka-processor-2
    depends_on:
      - zookeeper
      - kafka
      - kafka-processor-1
    volumes:
      - ./processor2:/app
    working_dir: /app
    command: python3 kafka_script.py

